version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: ai-intl-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
